#!/usr/bin/env bash

issemver=$(./scripts/check-semver.sh -t "$TAG_NAME")
currenttag=$(npm pkg get version)

git config user.name github-actions
git config user.email github-actions@github.com

if [ "$issemver" -eq "1" ]; then
    echo "Publishing version $TAG_NAME"

    if ! [ "$currenttag" = "\"$TAG_NAME\"" ]; then
        echo "Branch tag is different than packge.json version. Updating package.json version to $TAG_NAME"
        npm version "$TAG_NAME"
    fi

    echo "Generating documentation"
    yarn generate-docs

    echo "Bundling examples"
    yarn bundle-examples $TAG_NAME

    git add --all
    git commit -m "docs: autogenerated documentation and examples"
    git tag -f -a $TAG_NAME -m $TAG_NAME

    echo "Pushing changes to origin"
    git push --no-verify
    git push --no-verify origin -f $TAG_NAME

    echo "Publishing to npm"
    npm publish
fi